server {
  listen 80;
  server_name _;

  location ^~/web/ {
    alias /usr/share/nginx/html/;
    index index.html;
    try_files $uri $uri/ /web/index.html;
  }

  # 访问根路径时，永久重定向到 /web/
  location = / {
    return 301 /web/;
  }

  # 可以选择将404页面也指向/web/的入口，以兼容路由
  error_page 404 /web/index.html;
}
